/**
 * Blog posts: the content source of truth for the `/blog/<slug>` dynamic route.
 * It mirrors `landing-pages.ts` so the blog reuses the same
 * `generateStaticParams` + `generateMetadata` pattern (see `/practice/[slug]`).
 *
 * Field meanings:
 *   - slug:           URL segment; the key used by generateStaticParams.
 *   - publishedAt:    ISO-8601 publish date (rendered as the article date).
 *   - lastModified:   ISO-8601 last edit date; used by sitemap and Article
 *                     structured data (`dateModified`).
 *   - ogImage:        Public path to a 1200x630 social card (generated by
 *                     scripts/generate-og-images.mjs as /og-<slug>.png).
 *   - locales.zh/en:  Per-language metadata and article body.
 *       - title / lead:      H1 and the summary paragraph under it.
 *       - metaTitle / metaDescription: <title> and meta description.
 *       - ogTitle / ogDescription / ogAlt: Open Graph / Twitter card copy.
 *       - sections:          Body sections; each has an H2 heading, paragraphs,
 *                            and optional bullets.
 */

export type Locale = "zh" | "en";

export type BlogSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type BlogLocale = {
  metaTitle: string;
  metaDescription: string;
  ogTitle: string;
  ogDescription: string;
  ogAlt: string;
  title: string;
  lead: string;
  sections: BlogSection[];
};

export type BlogPost = {
  slug: string;
  publishedAt: string;
  lastModified: string;
  ogImage: string;
  locales: Record<Locale, BlogLocale>;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "intensive-listening-method",
    publishedAt: "2026-09-01",
    lastModified: "2026-09-01",
    ogImage: "/og-intensive-listening-method.png",
    locales: {
      zh: {
        metaTitle: "什么是精听？精听的正确步骤（逐句精听方法）",
        metaDescription:
          "精听怎么做才有效？这篇指南讲清精听与泛听的区别、逐句精听的正确步骤（先听、判断、核对、重复），以及单句循环和变速怎么用，帮你真正听懂每一句。",
        ogTitle: "什么是精听？精听的正确步骤",
        ogDescription: "逐句精听的正确步骤：先听、判断、核对、重复，配合单句循环与变速，练到真正听懂。",
        ogAlt: "DuolinTing 多邻听——精听方法与逐句精听步骤",
        title: "什么是精听？精听的正确步骤",
        lead: "泛听让你跟上大意，精听才让你听懂每一个词。这篇指南把精听拆成一套可以照做的步骤，并讲清单句循环、变速这些工具到底该怎么用。",
        sections: [
          {
            heading: "为什么「泛听很久了还是听不懂」",
            paragraphs: [
              "很多学习者的做法是：把播客、新闻当背景音一直放，期待「磨耳朵」磨出语感。泛听确实能帮你熟悉节奏和语调，但它有一个天花板——它不强迫你面对那些真正听不清的连读、弱读和生词。",
              "结果是：大意能跟上，一具体到某句话说了什么，就卡住了。这个缺口，正是精听要补的地方。",
            ],
          },
          {
            heading: "精听和泛听的区别",
            paragraphs: [
              "泛听关注整体：主题是什么、说话人是谁、态度是什么。精听关注局部：这一句的每一个词、每一个语音细节是什么。",
              "两者不是二选一，而是先后配合。先泛听建立上下文，再精听攻克细节，最后把难点留下来复习。DuolinTing 的三阶段练习就是按这个顺序组织的。",
            ],
            bullets: [
              "泛听：完整听一遍，抓大意、不逐句回看",
              "精听：按时间轴逐句练，先听后核对",
              "复习：集中重练标记出来的难点句子",
            ],
          },
          {
            heading: "精听的正确步骤：先听、判断、核对、重复",
            paragraphs: [
              "每一句都按同一套动作来，顺序很重要——先听、再判断、再核对。",
              "第一步，只听不看，把这一句完整听一遍。第二步，判断自己听到了什么，最好说出来或写下来。第三步，再核对字幕或译文，找出漏听和误听的地方。第四步，对出错的地方循环重听，直到不再需要刻意就能听懂。",
              "「先听再核对」是精听和「边看字幕边听」的本质区别。先看字幕会跳过辨音这个最关键的过程——你会以为自己听懂了，其实只是读懂了。",
            ],
          },
          {
            heading: "单句循环和变速怎么用",
            paragraphs: [
              "遇到连读、弱读或语速过快的句子，别急着看答案。先用单句循环把这一句隔离出来；仍听不清时，放慢速度逐个词辨清；最后回到原速，反复听直到自然跟上。",
              "变速的价值在于「阶梯式」逼近原速：先慢速听清，再逐步加速，让耳朵适应真实的语速，而不是一直依赖慢速。",
            ],
            bullets: [
              "单句循环：把一句隔离出来反复听",
              "变速播放：先慢速辨清，再回到原速",
              "难点标记：把仍不稳的句子留给复习阶段",
            ],
          },
          {
            heading: "精听之后：把难点交给复习",
            paragraphs: [
              "精听完不等于结束。把听错的、需要反复重听的句子标记为难点，集中起来复习，是把「听懂过一次」变成「一直听得懂」的关键。",
              "DuolinTing 的难点复习阶段会自动汇聚你标记的句子，让你不用在整段材料里大海捞针。",
            ],
          },
          {
            heading: "三个常见误区",
            paragraphs: [
              "第一，边看字幕边听，以为自己在精听——这跳过了辨音。第二，一句无限重听直到「顺下来」——那练的是瞬时记忆，不是辨音能力。第三，贪多求快，一次精听大量材料——精听重质不重量，把几句练透，胜过草草过十段。",
            ],
          },
        ],
      },
      en: {
        metaTitle: "What Is Intensive Listening? A Line-by-Line Method",
        metaDescription:
          "How to do intensive listening effectively: the difference between extensive and intensive listening, the line-by-line steps (listen, decide, check, repeat), and how to use looping and speed control to truly understand each line.",
        ogTitle: "What Is Intensive Listening? A Line-by-Line Method",
        ogDescription: "Line-by-line intensive listening: listen, decide, check, repeat - with looping and speed control.",
        ogAlt: "DuolinTing - intensive listening and line-by-line method",
        title: "What Is Intensive Listening? A Line-by-Line Method",
        lead: "Extensive listening keeps you on the big picture; intensive listening makes you understand every word. This guide breaks intensive listening into a repeatable set of steps and explains how to use looping and speed control the right way.",
        sections: [
          {
            heading: "Why \"lots of extensive listening\" still leaves you stuck",
            paragraphs: [
              "A common approach is to leave podcasts and news running in the background and hope your ear \"absorbs\" the language. Extensive listening does build familiarity with rhythm and intonation, but it has a ceiling - it never forces you to face the connected speech, weak forms, and unknown words you actually miss.",
              "The result: you follow the gist, but the moment you need a specific sentence, you stall. That gap is exactly what intensive listening closes.",
            ],
          },
          {
            heading: "Extensive vs intensive listening",
            paragraphs: [
              "Extensive listening is about the whole: the topic, the speaker, the attitude. Intensive listening is about the parts: every word and sound detail in one line.",
              "They aren't either-or; they work in sequence. Warm up extensively to build context, practice intensively to crack the details, then review the hard parts. DuolinTing's three-stage path is organized in exactly this order.",
            ],
            bullets: [
              "Extensive: listen through once, grasp the gist, don't rewind",
              "Intensive: practice line by line on the timeline, listen then check",
              "Review: replay the difficult lines you marked",
            ],
          },
          {
            heading: "The right steps: listen, decide, check, repeat",
            paragraphs: [
              "Practice every line with the same routine, and the order matters - listen, decide, then check.",
              "First, listen to the line once without reading. Second, decide what you heard, ideally saying or writing it down. Third, check the subtitles or translation to find what you missed or misheard. Fourth, loop the parts you got wrong until you understand them without effort.",
              "The \"listen before you check\" order is what separates intensive listening from merely reading along. Checking first skips the recognition step that matters most - you'll think you heard it when you really only read it.",
            ],
          },
          {
            heading: "How to use looping and speed control",
            paragraphs: [
              "When you hit connected speech, weak forms, or fast lines, don't reach for the answer. First isolate the line with single-line looping; if it's still unclear, slow down and make out each word; then return to full speed and repeat until you follow naturally.",
              "Speed control works best as a ladder back to full speed: hear it slow first, then step up, so your ear adapts to real-world pace instead of depending on slow audio.",
            ],
            bullets: [
              "Single-line loop: isolate one line and repeat",
              "Speed control: hear it slow first, then return to full speed",
              "Difficult marking: leave unstable lines for review",
            ],
          },
          {
            heading: "After intensive listening: hand the hard parts to review",
            paragraphs: [
              "Intensive listening isn't the finish line. Mark the lines you got wrong or had to replay, and review them together - that's what turns \"I understood it once\" into \"I still understand it.\"",
              "DuolinTing's difficult-review stage gathers the lines you mark automatically, so you never have to hunt through a whole passage.",
            ],
          },
          {
            heading: "Three common mistakes",
            paragraphs: [
              "First, reading subtitles while listening and calling it intensive practice - that skips recognition. Second, replaying one line until you can parrot it - that trains short-term memory, not recognition. Third, doing too much at once - intensive listening is about quality; a few lines practiced deeply beat ten passages skimmed.",
            ],
          },
        ],
      },
    },
  },
  {
    slug: "youzack-alternative",
    publishedAt: "2026-09-01",
    lastModified: "2026-09-01",
    ogImage: "/og-youzack-alternative.png",
    locales: {
      zh: {
        metaTitle: "YouZack 替代：用 DuolinTing 做逐句精听与听写",
        metaDescription:
          "在找类似 YouZack 的听力工具？DuolinTing 是受 YouZack 听力学习理念启发的独立开源项目，支持真实材料的泛听、逐句精听、听写与难点复习，可自部署。",
        ogTitle: "YouZack 替代｜用 DuolinTing 做逐句精听与听写",
        ogDescription: "独立开源的逐句精听工具：真实材料 + 泛听/精听/听写/难点复习，可自部署。",
        ogAlt: "DuolinTing 多邻听——受 YouZack 理念启发的独立听力工具",
        title: "YouZack 替代：用 DuolinTing 做逐句精听与听写",
        lead: "如果你喜欢 YouZack「用真实材料逐句精听」的思路，想找一个开源、可自部署、能自己制课的替代方案，DuolinTing 提供了一条相近又独立的路径。",
        sections: [
          {
            heading: "先说明白我们的关系",
            paragraphs: [
              "DuolinTing（多邻听）是受 YouZack 听力学习理念启发的独立开源项目。我们尊重 YouZack 对「真实材料 + 逐句精听」这个方法的坚持，也明确声明：DuolinTing 并非 YouZack 官方产品，也不代表获得其官方背书。",
              "这意味着你可以把 DuolinTing 当成一个「理念相近、实现独立」的选择来评估，而不是一个官方替代。",
            ],
          },
          {
            heading: "共同点：真实材料，逐句听懂",
            paragraphs: [
              "两者都反对把听力练成脱离语境的机械题。核心体验是一致的：拿一段真实的播客、访谈或新闻，先整体听一遍，再逐句精听，把真正没听懂的部分留下来反复练。",
              "DuolinTing 把这条路径组织成三个阶段：泛听热身、逐句精听、难点复习。每一句都支持先听、判断、核对，以及单句循环和变速播放。",
            ],
            bullets: [
              "泛听热身：完整听一遍，建立上下文",
              "逐句精听：先听、判断、核对、循环",
              "难点复习：集中重练标记的困难句子",
            ],
          },
          {
            heading: "不同点：开源、自部署、自己制课",
            paragraphs: [
              "DuolinTing 以 Apache-2.0 开源。你可以自己部署一套，也可以用自己的合法内容建立听力资料库——上传媒体、导入字幕、校准逐句时间轴、补充翻译，然后发布给学习者。",
              "制课流程集中在管理后台：目录结构、课程管理、制课工作台、字幕导入、波形校准、发布检查，一条龙完成。如果你有一批自己的 SRT 字幕或合法媒体，可以直接把它们变成能练的听力课。",
            ],
          },
          {
            heading: "怎么把学习习惯迁移过来",
            paragraphs: [
              "如果你习惯了 YouZack 的节奏，迁移成本很低：选一段你关心的真实材料，先泛听热身，再逐句精听，遇到难点标记出来，最后集中复习。听写和生词本也都在精听流程里，不会打断你的节奏。",
              "网页端打开即用，无需安装；Android 用户可以从官网下载 APK。",
            ],
          },
          {
            heading: "开始之前",
            paragraphs: [
              "请使用你拥有使用权的媒体和字幕。DuolinTing 的贡献指南写明了内容与授权规则，也会公开署名校对与审核贡献者。如果你只是想练听力，直接打开网页端即可开始。",
            ],
          },
        ],
      },
      en: {
        metaTitle: "YouZack Alternative: Line-by-Line Listening with DuolinTing",
        metaDescription:
          "Looking for a YouZack-style listening tool? DuolinTing is an independent open-source project inspired by YouZack's approach - real-material extensive listening, line-by-line practice, dictation, and review, self-hostable.",
        ogTitle: "YouZack Alternative | Line-by-Line Listening with DuolinTing",
        ogDescription: "An independent open-source line-by-line listening tool: real material, intensive practice, and self-hosting.",
        ogAlt: "DuolinTing - an independent listening tool inspired by YouZack's approach",
        title: "YouZack Alternative: Line-by-Line Listening with DuolinTing",
        lead: "If you like YouZack's idea of turning real material into line-by-line practice and want an open-source, self-hostable option with your own course creation, DuolinTing offers a similar but independent path.",
        sections: [
          {
            heading: "Let's be clear about the relationship",
            paragraphs: [
              "DuolinTing is an independent open-source project inspired by YouZack's approach to listening practice. We respect YouZack's commitment to the \"real material + line-by-line listening\" method, and we say plainly: DuolinTing is not an official YouZack product and is not endorsed by YouZack.",
              "That means you can evaluate DuolinTing as a \"similar philosophy, independent implementation\" option - not an official replacement.",
            ],
          },
          {
            heading: "What's shared: real material, understood line by line",
            paragraphs: [
              "Both reject the idea of reducing listening to decontextualized drills. The core experience is the same: take a real podcast, interview, or news clip, listen through once for the whole, then practice line by line and keep the parts you still miss for review.",
              "DuolinTing organizes this path into three stages: warm-up listening, line-by-line practice, and difficult-line review. Every line supports listen-first, decide, then check, plus single-line looping and speed control.",
            ],
            bullets: [
              "Warm up: listen through once to build context",
              "Intensive: listen, decide, check, then loop",
              "Review: replay the difficult lines you marked",
            ],
          },
          {
            heading: "What's different: open source, self-hostable, build your own lessons",
            paragraphs: [
              "DuolinTing is open source under Apache-2.0. You can self-host a copy, and you can build a listening library from media you have the right to use - upload media, import subtitles, align line timing, add translations, then publish for learners.",
              "Course creation lives in one admin workspace: catalogue structure, course management, the creation workbench, subtitle import, waveform alignment, and publish checks. If you have a batch of SRT subtitles or rights-cleared media, you can turn them into practiceable lessons.",
            ],
          },
          {
            heading: "How to migrate your habit",
            paragraphs: [
              "If you're used to YouZack's rhythm, the switch is cheap: pick a real piece you care about, warm up extensively, practice line by line, mark the hard parts, then review them together. Dictation and the vocabulary notebook live inside the same flow, so nothing interrupts your pace.",
              "The web learner opens with no install; Android users can download the APK from the official site.",
            ],
          },
          {
            heading: "Before you start",
            paragraphs: [
              "Use only media and subtitles you have the right to use. DuolinTing's contribution guide spells out the content and rights rules, and it publicly credits proofreaders and reviewers. If you just want to practice listening, open the web learner and start.",
            ],
          },
        ],
      },
    },
  },
  {
    slug: "srt-to-listening-practice",
    publishedAt: "2026-09-01",
    lastModified: "2026-09-01",
    ogImage: "/og-srt-to-listening-practice.png",
    locales: {
      zh: {
        metaTitle: "如何把 SRT 字幕做成逐句听力练习",
        metaDescription:
          "手头有 SRT 字幕怎么练听力？这篇指南讲清如何把 SRT/VTT/ASS/LRC 字幕导入、校准时间轴，变成可以逐句精听、听写和复习的听力课。",
        ogTitle: "如何把 SRT 字幕做成逐句听力练习",
        ogDescription: "把 SRT/VTT/ASS/LRC 字幕导入、校准、变成逐句精听与听写的听力课。",
        ogAlt: "DuolinTing 多邻听——把 SRT 字幕做成逐句听力练习",
        title: "如何把 SRT 字幕做成逐句听力练习",
        lead: "字幕文件里其实藏着现成的听力课——每一句都有原文和时间轴。这篇指南讲清怎么把它导入、校准，变成可以逐句精听、听写和复习的练习。",
        sections: [
          {
            heading: "为什么 SRT 字幕适合做听力练习",
            paragraphs: [
              "SRT 字幕的每一行都包含两样东西：一句原文，和它出现的时间区间。这正好是逐句精听需要的素材——一句一个练习单元，时间轴负责在播放时精确定位。",
              "把字幕和对应的音频或视频一起导入，你就得到了一门可以逐句练的课，比从零手动切句子省太多时间。",
            ],
          },
          {
            heading: "第一步：确认素材和时间轴",
            paragraphs: [
              "开始前确认两件事。第一，你对这段媒体和字幕拥有使用权——自己创作、已获授权，或开放许可允许此用途。第二，时间轴要准确：逐句精听依赖精确的起止时间，错位的字幕会让「按句循环」对不上音频。",
            ],
            bullets: [
              "确认媒体与字幕的使用权",
              "检查时间轴是否与音频对齐",
              "双语字幕先确定哪一行是原文",
            ],
          },
          {
            heading: "第二步：导入字幕",
            paragraphs: [
              "DuolinTing 的制课工作台支持 .srt、.vtt、.ass、.lrc 和 .txt 字幕，也可以直接粘贴文本。导入后会得到一份字幕草稿，还需要和媒体逐句核对。",
              "如果是双语字幕，导入时选择「第一行是中文」或「第二行是中文」，让系统正确识别原文与译文。整体时间偏移用毫秒为单位调整，改完再抽查开头、中段和结尾。",
            ],
          },
          {
            heading: "第三步：在波形上校准每一句",
            paragraphs: [
              "导入只是起点。在波形和时间轴上逐句检查：拖动或缩放波形调整每句的开始与结束，确保片段紧贴实际说话范围——不切掉首尾音，也不把两句应分开的内容合并。",
              "这一步直接决定学习者按句循环、听写和复习时是否顺畅，值得花时间做好。",
            ],
            bullets: [
              "拖动波形调整每句起止",
              "需要时新增、合并或删除句子",
              "补齐原文、译文和可接受答案",
            ],
          },
          {
            heading: "第四步：把它变成逐句精听流程",
            paragraphs: [
              "校准完成后，这门课就能进入三阶段练习：先泛听热身，建立整体认识；再逐句精听，先听、判断、核对；遇到听写的部分，把听到的写下来再核对字幕与翻译。",
              "听写里暴露的拼写错误，顺手收进生词本；反复听不清的句子标记为难点，交给复习阶段集中处理。",
            ],
          },
          {
            heading: "想参与制课？",
            paragraphs: [
              "DuolinTing 是开源项目，内容协作由维护者配置账号。如果你愿意用自己的合法内容做课，可以从贡献指南了解完整流程。",
            ],
          },
        ],
      },
      en: {
        metaTitle: "How to Turn SRT Subtitles into Line-by-Line Listening Practice",
        metaDescription:
          "Got SRT subtitles? This guide shows how to import SRT/VTT/ASS/LRC subtitles, align the timeline, and turn them into line-by-line intensive listening, dictation, and review practice.",
        ogTitle: "How to Turn SRT Subtitles into Line-by-Line Listening Practice",
        ogDescription: "Import SRT/VTT/ASS/LRC subtitles, align the timeline, and turn them into intensive listening practice.",
        ogAlt: "DuolinTing - turning SRT subtitles into line-by-line listening practice",
        title: "How to Turn SRT Subtitles into Line-by-Line Listening Practice",
        lead: "A subtitle file already contains a ready-made listening lesson - every line has source text and a timestamp. This guide shows how to import it, align it, and turn it into line-by-line intensive listening, dictation, and review.",
        sections: [
          {
            heading: "Why SRT subtitles are perfect for listening practice",
            paragraphs: [
              "Every SRT entry carries two things: one line of source text, and the time range it appears. That's exactly what line-by-line listening needs - one sentence per practice unit, with the timeline locating it precisely during playback.",
              "Import subtitles together with their audio or video, and you get a practiceable lesson, saving hours versus manually slicing sentences from scratch.",
            ],
          },
          {
            heading: "Step one: confirm the material and timeline",
            paragraphs: [
              "Confirm two things before you start. First, you have the rights to the media and subtitles - your own work, licensed, or covered by an open licence that permits this use. Second, the timeline is accurate: line-by-line practice depends on precise start and end times, and misaligned subtitles make per-line looping drift from the audio.",
            ],
            bullets: [
              "Confirm the rights to the media and subtitles",
              "Check that the timeline matches the audio",
              "For bilingual subtitles, decide which line is the source",
            ],
          },
          {
            heading: "Step two: import the subtitles",
            paragraphs: [
              "DuolinTing's creation workspace accepts .srt, .vtt, .ass, .lrc, and .txt subtitles, and you can paste text directly. Importing produces a subtitle draft that still needs a line-by-line check against the media.",
              "For bilingual subtitles, choose \"first line is Chinese\" or \"second line is Chinese\" so the system reads source and translation correctly. Use the millisecond global offset for whole-track shifts, then sample the beginning, middle, and end.",
            ],
          },
          {
            heading: "Step three: align every line on the waveform",
            paragraphs: [
              "Importing is just the start. Work line by line on the waveform and timeline: drag or zoom to adjust each segment's start and end so it matches the spoken range - don't cut off word beginnings or endings, and don't merge two lines that should be practiced separately.",
              "This step directly determines whether per-line looping, dictation, and review feel smooth, so it's worth doing carefully.",
            ],
            bullets: [
              "Drag the waveform to adjust each line's start and end",
              "Add, merge, or delete lines as needed",
              "Complete source text, translations, and accepted answers",
            ],
          },
          {
            heading: "Step four: turn it into a line-by-line flow",
            paragraphs: [
              "Once aligned, the lesson enters the three-stage path: warm up extensively to build the overall picture; practice intensively line by line with listen, decide, then check; and for dictation, write what you hear before checking subtitles and translation.",
              "Save spelling mistakes from dictation to your vocabulary, and mark lines that stay unclear as difficult for the review stage.",
            ],
          },
          {
            heading: "Want to contribute lessons?",
            paragraphs: [
              "DuolinTing is an open-source project, and content collaboration is provisioned by maintainers. If you'd like to build lessons from content you have the rights to, start with the contribution guide.",
            ],
          },
        ],
      },
    },
  },
];

/** Look up a single blog post by its URL slug. Returns undefined for unknown slugs. */
export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}

/** Localized public path for a blog post: `/blog/<slug>` or `/en/blog/<slug>`. */
export function blogPostPath(slug: string, locale: Locale): string {
  const base = `/blog/${slug}`;
  return locale === "en" ? `/en${base}` : base;
}
