/**
 * Feature landing pages: the content source of truth for the `[slug]` dynamic
 * route (`/practice/<slug>` for Chinese, `/en/practice/<slug>` for English).
 *
 * Each entry is one self-contained, indexable landing page. The page keeps its
 * own metadata (title / description / Open Graph) and body copy so a single
 * template can render every page via `generateStaticParams` + `generateMetadata`.
 *
 * How to add a page (or later a blog post under the same pattern):
 *   1. Add an entry to `landingPages` below with a unique `slug`.
 *   2. Keep `lastModified` in sync with the "last updated" line the template
 *      renders and with the entry added to `app/sitemap.ts`.
 *   3. Generate its social card with `node scripts/generate-og-images.mjs`
 *      and point `ogImage` at `/og-<slug>.png`.
 *
 * Field meanings:
 *   - slug:          URL segment; also the key used by generateStaticParams.
 *   - lastModified:  ISO-8601 date of the last content edit. Used by sitemap
 *                    and rendered as the page's "last updated" line.
 *   - ogImage:       Public path to the 1200x630 social card (generated by
 *                    scripts/generate-og-images.mjs).
 *   - locales.zh/en: Per-language metadata and body copy.
 *       - metaTitle/Description: <title> and meta description for the page.
 *         The root layout appends "｜DuolinTing 多邻听" via the title template.
 *       - ogTitle/Description:   Open Graph / Twitter card copy.
 *       - ogAlt:                 Alt text for the social card image.
 *       - hero:                  H1 area (eyebrow kicker, title, lead).
 *       - sections:              Body sections (eyebrow, H2, paragraph, bullets).
 *       - faq:                   FAQPage items; also rendered on-page.
 */

export type Locale = "zh" | "en";

export type LandingSection = {
  eyebrow: string;
  title: string;
  body: string;
  bullets?: string[];
};

export type LandingFaq = {
  question: string;
  answer: string;
};

export type LandingLocale = {
  metaTitle: string;
  metaDescription: string;
  ogTitle: string;
  ogDescription: string;
  ogAlt: string;
  hero: { eyebrow: string; title: string; lead: string };
  sections: LandingSection[];
  faq: LandingFaq[];
};

export type LandingPage = {
  slug: string;
  lastModified: string;
  ogImage: string;
  locales: Record<Locale, LandingLocale>;
};

export const landingPages: LandingPage[] = [
  {
    slug: "extensive-listening",
    lastModified: "2026-09-01",
    ogImage: "/og-extensive-listening.png",
    locales: {
      zh: {
        metaTitle: "泛听练习：先听懂大意，再进入细节",
        metaDescription:
          "什么是泛听？用真实播客、访谈和新闻做泛听热身，完整听一遍、建立对主题和语境的整体认识，再进入逐句精听。DuolinTing 多邻听的泛听练习方法。",
        ogTitle: "泛听练习｜英语听力热身方法",
        ogDescription: "用真实材料做泛听热身：先听懂大意、建立语感，再进入逐句精听。",
        ogAlt: "DuolinTing 多邻听——泛听练习方法",
        hero: {
          eyebrow: "泛听热身 · 第一阶段",
          title: "先听懂大意，再进入细节。",
          lead: "泛听是 DuolinTing 三阶段练习的第一步：完整听一遍，建立对主题、说话人和语境的整体认识，不急着抠每一个词。",
        },
        sections: [
          {
            eyebrow: "什么是泛听",
            title: "泛听不是随便听，而是有目标的整体理解。",
            body: "泛听要求你先放下“每个词都听懂”的执念，只关注这段材料在讲什么、谁在说话、大致脉络是什么。它解决的是“一头扎进细节却丢了全局”的常见问题，为后面的逐句精听建立上下文。",
            bullets: [
              "完整听一遍，不暂停、不逐句回看",
              "只抓主题、说话人和大致脉络",
              "为下一步逐句精听建立上下文",
            ],
          },
          {
            eyebrow: "为什么先泛听",
            title: "先整体、后局部，挫败感会低很多。",
            body: "直接逐句精听真实材料，往往在第一句就被生词和连读卡住。先泛听一遍，你知道这段在谈什么，再去攻克细节时，很多原本“听不出”的地方会因为有了预期而变得可辨。",
            bullets: [
              "降低面对真实语速的挫败感",
              "用上下文帮助后续辨音",
              "更接近真实的听力使用场景",
            ],
          },
          {
            eyebrow: "在 DuolinTing 里怎么做",
            title: "把第一遍泛听，变成可重复的热身。",
            body: "DuolinTing 的泛听热身阶段让你先完整播放一段真实材料，只做整体理解。听完后再进入逐句精听，把真正没听懂的部分留下来复习。整个过程围绕同一段材料，不会在多个工具之间跳来跳去。",
            bullets: [
              "先用真实音视频完整听一遍",
              "确认主题与说话人后进入精听",
              "听不清的句子自动成为复习重点",
            ],
          },
        ],
        faq: [
          {
            question: "泛听和精听有什么区别？",
            answer: "泛听关注整体：听懂大意、主题和说话人的态度；精听关注局部：把每一句、每个词辨清。DuolinTing 把两者接成一条路径——先泛听热身，再逐句精听，最后复习难点。",
          },
          {
            question: "泛听时遇到听不懂的词要停下来吗？",
            answer: "不要。泛听阶段先顺着往下听，尽量抓大意。卡住你的词往往会在后面的逐句精听中，因为有了上下文而变得更容易辨清。",
          },
          {
            question: "每次泛听多长时间比较合适？",
            answer: "以一段完整的真实材料为宜，比如一条几分钟的播客或新闻片段。关键是完整听一遍、形成整体印象，而不是追求时长。",
          },
        ],
      },
      en: {
        metaTitle: "Extensive Listening: Grasp the Big Picture First",
        metaDescription:
          "What is extensive listening? Warm up with real podcasts, interviews, and news: listen through once to grasp the topic and context before line-by-line intensive practice. DuolinTing's extensive listening method.",
        ogTitle: "Extensive Listening | English Listening Warm-Up",
        ogDescription: "Warm up with real material: grasp the big picture first, then practice line by line.",
        ogAlt: "DuolinTing — extensive listening practice method",
        hero: {
          eyebrow: "Warm-up listening · Stage one",
          title: "Grasp the big picture before the details.",
          lead: "Extensive listening is the first stage of DuolinTing's three-stage path: listen through once to understand the topic, speakers, and context—without trying to catch every word.",
        },
        sections: [
          {
            eyebrow: "What is extensive listening",
            title: "Extensive listening is purposeful whole-passage understanding.",
            body: "Extensive listening means letting go of the need to catch every word and focusing on what the material is about, who is speaking, and the overall flow. It solves the common trap of diving into details while losing the whole, and it sets up the context for line-by-line practice.",
            bullets: [
              "Listen through once—no pausing, no rewinding",
              "Catch only the topic, speakers, and overall flow",
              "Build context for line-by-line practice next",
            ],
          },
          {
            eyebrow: "Why listen extensively first",
            title: "Whole first, parts second—less frustration.",
            body: "Diving straight into line-by-line practice on real material often stalls at the first unknown word or connected speech. When you listen extensively first, you know what the passage is about, and details that once felt impossible become recognizable because you have expectations.",
            bullets: [
              "Lower the frustration of real-world speed",
              "Use context to make later sound recognition easier",
              "Mirror how listening actually happens",
            ],
          },
          {
            eyebrow: "How DuolinTing helps",
            title: "Turn the first pass into a repeatable warm-up.",
            body: "DuolinTing's warm-up stage lets you play a piece of real material once through and focus only on overall understanding. Then you move into line-by-line practice and keep the parts that are still unclear for review—all around the same material, with no jumping between tools.",
            bullets: [
              "Listen through real audio or video once",
              "Confirm the topic and speakers, then practice line by line",
              "Unclear lines automatically become review targets",
            ],
          },
        ],
        faq: [
          {
            question: "What is the difference between extensive and intensive listening?",
            answer: "Extensive listening focuses on the whole: the main idea, topic, and speaker's attitude. Intensive listening focuses on the parts: recognizing each line and word. DuolinTing connects them into one path—warm up extensively, practice intensively, then review what is hard.",
          },
          {
            question: "Should I stop when I hear an unknown word?",
            answer: "No. During extensive listening, keep going and try to grasp the main idea. Words that trip you up usually become easier to recognize later, during line-by-line practice, because you now have context.",
          },
          {
            question: "How long should each extensive session be?",
            answer: "One complete piece of real material works well—for example, a few-minute podcast or news clip. The point is to listen through once and form an overall impression, not to chase a certain duration.",
          },
        ],
      },
    },
  },
  {
    slug: "intensive-listening",
    lastModified: "2026-09-01",
    ogImage: "/og-intensive-listening.png",
    locales: {
      zh: {
        metaTitle: "精听方法：逐句精听的正确步骤",
        metaDescription:
          "精听怎么做才有效？掌握逐句精听步骤：先听、再判断、再核对，配合单句循环与变速播放，把真正听不懂的句子练到听懂。DuolinTing 多邻听的精听练习方法。",
        ogTitle: "精听方法｜逐句精听的正确步骤",
        ogDescription: "逐句精听：先听、再判断、再核对，配合单句循环与变速，练到真正听懂。",
        ogAlt: "DuolinTing 多邻听——精听方法与逐句精听步骤",
        hero: {
          eyebrow: "逐句精听 · 第二阶段",
          title: "把每一句，练到真正听懂。",
          lead: "精听是 DuolinTing 三阶段练习的核心：按时间轴练习每一句——先听、再判断、再核对，把真正没听懂的句子留下来反复练。",
        },
        sections: [
          {
            eyebrow: "什么是精听",
            title: "精听是把一段材料拆成可攻克的句子。",
            body: "泛听解决整体理解，精听解决“这句话到底说了什么”。它把真实材料切成一句一句的练习单元，让你在一句上集中注意力，而不是被整段的语速压垮。",
            bullets: [
              "把连续语流拆成逐句练习单元",
              "在一句上反复听、反复核对",
              "把注意力集中到真正难的地方",
            ],
          },
          {
            eyebrow: "精听的正确步骤",
            title: "先听、再判断、再核对。",
            body: "每句都按同一套动作练习：先只听不看的听一遍，判断自己听到了什么；再看字幕或译文核对；最后把听错的、没听清的部分留下来重复。这个“先想再看”的顺序，是精听和“边看字幕边听”的关键区别。",
            bullets: [
              "先听一遍，说出或写下你听到的内容",
              "再核对原文，找出漏听与误听",
              "对难点句子循环重听直到听懂",
            ],
          },
          {
            eyebrow: "单句循环与变速",
            title: "用循环和变速，攻克最难的那几句。",
            body: "DuolinTing 支持单句循环和播放速度调节。遇到连读、弱读或语速过快的句子，可以放慢速度先听清，再逐步回到原速，直到能在正常语速下听懂。",
            bullets: [
              "单句循环：把一句练到稳定听懂",
              "变速播放：先慢速辨清，再回到原速",
              "难点标记：把困难句子留给复习阶段",
            ],
          },
        ],
        faq: [
          {
            question: "精听一篇材料要多久？",
            answer: "取决于材料长度和你的水平。几分钟的片段，逐句精听通常需要比材料本身长几倍的时间。不必一次精听完，可以分段完成，重点是把每一句都练到位。",
          },
          {
            question: "精听时要不要先看字幕？",
            answer: "建议先听、不看字幕，判断自己听到了什么，再核对。先看字幕会跳过“辨音”这个最关键的过程；先听后看才能知道问题出在哪儿。",
          },
          {
            question: "单句循环怎么用最有效？",
            answer: "对听不清的句子，先原速再听一遍；仍听不清时放慢速度辨清每个词；最后回到原速反复听，直到不用刻意也能跟上。之后把仍不稳的句子标记为难点，交给复习阶段。",
          },
        ],
      },
      en: {
        metaTitle: "Intensive Listening: How to Practice Line by Line",
        metaDescription:
          "How to do intensive listening effectively? Master the line-by-line steps—listen, decide, then check—with single-line looping and speed control to truly understand each sentence. DuolinTing's intensive listening method.",
        ogTitle: "Intensive Listening | Line-by-Line Practice Method",
        ogDescription: "Line-by-line intensive listening: listen, decide, check—with looping and speed control.",
        ogAlt: "DuolinTing — intensive listening and line-by-line practice method",
        hero: {
          eyebrow: "Line-by-line listening · Stage two",
          title: "Practice each line until you truly understand it.",
          lead: "Intensive listening is the core of DuolinTing's three-stage path: practice each line on the timeline—listen first, decide what you heard, then check—and keep the lines you still miss for review.",
        },
        sections: [
          {
            eyebrow: "What is intensive listening",
            title: "Intensive listening breaks material into conquerable lines.",
            body: "Extensive listening handles the whole; intensive listening handles the question “what exactly did this sentence say?” It cuts real material into line-by-line practice units so you can focus on one sentence instead of being overwhelmed by a full-speed passage.",
            bullets: [
              "Break continuous speech into line-by-line units",
              "Listen and check one sentence at a time",
              "Focus attention where it is actually hard",
            ],
          },
          {
            eyebrow: "The right steps",
            title: "Listen, decide, then check.",
            body: "Practice every line with the same routine: listen first without reading and decide what you heard; then check the subtitles or translation; finally, repeat the parts you missed. This “think before you look” order is what separates intensive listening from merely reading along.",
            bullets: [
              "Listen once and say or write what you heard",
              "Check against the source to find gaps and mis-hearings",
              "Loop the difficult lines until they are clear",
            ],
          },
          {
            eyebrow: "Looping and speed",
            title: "Use looping and speed to crack the hardest lines.",
            body: "DuolinTing supports single-line looping and playback speed control. For connected speech, weak forms, or fast lines, slow down to hear each word, then build back up to full speed until you understand it naturally.",
            bullets: [
              "Single-line loop: repeat until a line is stable",
              "Speed control: slow down to hear, then return to full speed",
              "Difficult-line marking: save hard lines for review",
            ],
          },
        ],
        faq: [
          {
            question: "How long does intensive listening take?",
            answer: "It depends on the material and your level. For a few-minute clip, line-by-line practice usually takes several times the clip's own length. You don't need to finish in one sitting—work in sections and make sure each line is genuinely practiced.",
          },
          {
            question: "Should I read the subtitles first?",
            answer: "Preferably not. Listen first without subtitles and decide what you heard, then check. Reading first skips the recognition step that matters most; listening first shows you where the problem actually is.",
          },
          {
            question: "How do I use single-line looping most effectively?",
            answer: "For a line you can't catch, listen once more at full speed; if it's still unclear, slow it down to hear each word; then return to full speed and repeat until you can follow without effort. Mark lines that stay unstable as difficult for the review stage.",
          },
        ],
      },
    },
  },
  {
    slug: "dictation",
    lastModified: "2026-09-01",
    ogImage: "/og-dictation.png",
    locales: {
      zh: {
        metaTitle: "英语听写练习：逐句听写提升辨音",
        metaDescription:
          "逐句听写是最扎实的精听方式。用 DuolinTing 做逐句听写：听原文、写下来、核对字幕与翻译，练出辨音、连读和拼写的准确性，把听力真正落地。",
        ogTitle: "英语听写练习｜逐句听写提升辨音",
        ogDescription: "逐句听写：听原文、写下来、核对字幕与翻译，练出辨音与拼写的准确性。",
        ogAlt: "DuolinTing 多邻听——逐句听写练习",
        hero: {
          eyebrow: "逐句听写 · 精听进阶",
          title: "把听到的写下来，才是真正的听清。",
          lead: "听写是精听里最“较真”的一步：先听一句，把它写下来，再核对字幕和翻译。它逼你面对每一个连读、弱读和拼写细节。",
        },
        sections: [
          {
            eyebrow: "为什么听写有效",
            title: "听写把“以为听懂”变成“真的写对”。",
            body: "很多人能“感觉听懂”，但写不出来。听写强制你逐词辨清，把模糊的语音变成明确的拼写，是最直接暴露听力短板的练习方式。",
            bullets: [
              "把模糊的语音变成明确拼写",
              "暴露连读、弱读和辨音盲点",
              "同时训练听力与拼写准确度",
            ],
          },
          {
            eyebrow: "怎么逐句听写",
            title: "一句一句来：听、写、核对。",
            body: "在 DuolinTing 里进入精听阶段后，对每句话先听一遍，写出你听到的内容；写不出来就单句循环或放慢速度；再核对原文与译文，找出漏掉和写错的地方。",
            bullets: [
              "先听一句，独立写出内容",
              "写不出时循环或放慢重听",
              "核对原文与译文，标注错误",
            ],
          },
          {
            eyebrow: "听写后的纠错",
            title: "错误才是进步最快的地方。",
            body: "核对后的错误不要跳过：区分是“没听清”还是“拼写不会”。没听清的交给单句循环练辨音；拼写不会的收进生词本。这样每次听写都能带走具体的进步。",
            bullets: [
              "区分辨音错误与拼写错误",
              "辨音问题用单句循环补",
              "生词拼写收进生词本复习",
            ],
          },
        ],
        faq: [
          {
            question: "听写要听多少遍？",
            answer: "以能独立写出为目标。先完整听一遍尝试写出，写不出再逐句循环或放慢速度，直到写完再核对。不要无限重复到“顺下来”为止，那样练的是记忆而非辨音。",
          },
          {
            question: "听写适合什么水平？",
            answer: "只要有基础词汇量就可以开始，关键是选择难度合适的真实材料——大约七成内容能听懂、三成需要攻克，进步最快。",
          },
          {
            question: "听写和精听有什么区别？",
            answer: "听写是精听的一种具体做法：精听强调先听后核对的整体流程，听写则额外要求把内容写出来，对辨音和拼写的要求更严格。",
          },
        ],
      },
      en: {
        metaTitle: "English Dictation Practice: Sharpen Listening Line by Line",
        metaDescription:
          "Line-by-line dictation is the most rigorous intensive listening. Dictate with DuolinTing: listen, write it down, then check subtitles and translations to build accurate sound recognition, connected speech, and spelling.",
        ogTitle: "English Dictation Practice | Line-by-Line Listening",
        ogDescription: "Dictate line by line: listen, write, then check—to build sound recognition and spelling accuracy.",
        ogAlt: "DuolinTing — line-by-line dictation practice",
        hero: {
          eyebrow: "Line-by-line dictation · intensive practice",
          title: "Writing down what you hear is real comprehension.",
          lead: "Dictation is the most exacting step in intensive listening: listen to a line, write it down, then check the subtitles and translation. It forces you to face every connected sound, weak form, and spelling detail.",
        },
        sections: [
          {
            eyebrow: "Why dictation works",
            title: "Dictation turns “I think I understood” into “I wrote it right.”",
            body: "Many people can feel they understood without being able to write it down. Dictation forces you to resolve each word, turning fuzzy sound into exact spelling—the most direct way to expose listening gaps.",
            bullets: [
              "Turn fuzzy sound into exact spelling",
              "Expose connected speech and sound-recognition gaps",
              "Train listening and spelling accuracy together",
            ],
          },
          {
            eyebrow: "How to dictate line by line",
            title: "One line at a time: listen, write, check.",
            body: "In DuolinTing's intensive stage, listen to each line once and write what you hear; loop it or slow it down if you can't write it; then check the source and translation to find what you missed or wrote wrong.",
            bullets: [
              "Listen to a line and write it independently",
              "Loop or slow down when you can't write it",
              "Check the source and translation, then mark errors",
            ],
          },
          {
            eyebrow: "Correcting after dictation",
            title: "Mistakes are where you improve fastest.",
            body: "Don't skip the errors you found: separate “didn't hear it” from “can't spell it.” Re-listen to sound-recognition gaps with single-line looping, and save spelling gaps to your vocabulary. Each session then ends with concrete progress.",
            bullets: [
              "Separate sound-recognition from spelling errors",
              "Fix recognition gaps with single-line looping",
              "Save new spelling to your vocabulary",
            ],
          },
        ],
        faq: [
          {
            question: "How many times should I listen during dictation?",
            answer: "Aim to write the line independently. Listen once through and try to write; if you can't, loop or slow down until you can, then check. Avoid repeating until you can just parrot it—that trains memory, not recognition.",
          },
          {
            question: "What level is dictation for?",
            answer: "You can start as soon as you have basic vocabulary. The key is choosing real material at the right difficulty—about 70% understandable and 30% to work on—for the fastest progress.",
          },
          {
            question: "What's the difference between dictation and intensive listening?",
            answer: "Dictation is one concrete form of intensive listening. Intensive listening is the overall listen-then-check flow; dictation additionally requires you to write the content out, demanding stricter sound recognition and spelling.",
          },
        ],
      },
    },
  },
  {
    slug: "vocabulary",
    lastModified: "2026-09-01",
    ogImage: "/og-vocabulary.png",
    locales: {
      zh: {
        metaTitle: "听力生词本：从语境里积累生词",
        metaDescription:
          "把听力里遇到的生词收进生词本，结合句子语境复习。DuolinTing 生词本帮你把听不清、听不懂的词，变成真正掌握的词汇。",
        ogTitle: "听力生词本｜从语境里积累生词",
        ogDescription: "把听力里的生词收进生词本，结合语境复习，把听不清的词变成真正掌握的词汇。",
        ogAlt: "DuolinTing 多邻听——听力生词本",
        hero: {
          eyebrow: "生词本 · 词汇积累",
          title: "听懂之后的生词，才是值得记住的词。",
          lead: "在逐句精听中遇到的生词，天然带着句子语境。把它们收进生词本，比孤立背单词表记得更牢、也更容易在真实听力里再次认出。",
        },
        sections: [
          {
            eyebrow: "为什么要从听力里记词",
            title: "语境记忆，比词表更接近真实使用。",
            body: "背单词表容易“见过但听不出”。从听力里收集生词，每个词都绑定真实发音和句子语境，再次听到时更容易被激活，记得也更牢。",
            bullets: [
              "每个生词都带真实发音与语境",
              "再次听到时更容易被激活",
              "比孤立背词表更接近真实使用",
            ],
          },
          {
            eyebrow: "怎么收集生词",
            title: "在精听和听写中随手收词。",
            body: "DuolinTing 让你在做逐句精听和听写时，把卡住你的词直接收进生词本。词条来自课程语境，而不是脱离上下文的孤立列表。",
            bullets: [
              "精听时标记听不懂的词",
              "听写后把拼写错误收进生词本",
              "每个词都带着所在句子的语境",
            ],
          },
          {
            eyebrow: "怎么复习生词",
            title: "回到语境，而不是只看释义。",
            body: "复习生词时，先回想它出现在哪句话里、怎么发音，再回到原句听一遍。用“听”来复习，而不是只背中文释义，才能把生词真正变成听力词汇。",
            bullets: [
              "先回想原句和发音",
              "回到原句再听一遍",
              "用“听”复习，而不是只背释义",
            ],
          },
        ],
        faq: [
          {
            question: "生词本和普通背单词有什么区别？",
            answer: "生词本里的词来自你正在练的真实材料，自带发音和句子语境；普通词表是脱离语境的孤立词汇。前者更容易在真实听力里再次认出。",
          },
          {
            question: "每个生词都要记吗？",
            answer: "不必。优先收进真正影响理解、且反复出现的词；一次性的专有名词或低频词可以放过，把时间留给高频实用词汇。",
          },
          {
            question: "生词多久复习一次？",
            answer: "建议在下次精听前快速回看一遍，并回到原句再听一次。结合新材料的持续输入，比严格的间隔算法更重要。",
          },
        ],
      },
      en: {
        metaTitle: "Listening Vocabulary: Build Words from Real Context",
        metaDescription:
          "Collect the words you meet while listening into a vocabulary notebook and review them in sentence context. DuolinTing helps you turn hard-to-hear words into vocabulary you truly know.",
        ogTitle: "Listening Vocabulary | Build Words from Context",
        ogDescription: "Collect listening vocabulary in context and review by ear, so new words become words you truly know.",
        ogAlt: "DuolinTing — listening vocabulary notebook",
        hero: {
          eyebrow: "Vocabulary · word building",
          title: "Words you meet after understanding are worth keeping.",
          lead: "New words you meet during line-by-line practice already carry sentence context. Saving them to your vocabulary beats memorizing isolated lists—and makes them easier to recognize in real listening again.",
        },
        sections: [
          {
            eyebrow: "Why build words from listening",
            title: "Context memory is closer to real use than word lists.",
            body: "Word lists often leave you “able to read but unable to hear.” Words collected from listening each carry real pronunciation and sentence context, so they activate more easily the next time you hear them.",
            bullets: [
              "Every word carries real sound and context",
              "Easier to activate when you hear it again",
              "Closer to real use than isolated word lists",
            ],
          },
          {
            eyebrow: "How to collect vocabulary",
            title: "Save words as you practice and dictate.",
            body: "DuolinTing lets you save the words that trip you up directly into your vocabulary while doing line-by-line practice and dictation. Entries come from course context, not from a detached list.",
            bullets: [
              "Mark words you can't catch during intensive practice",
              "Save spelling mistakes after dictation",
              "Every entry keeps the sentence context it came from",
            ],
          },
          {
            eyebrow: "How to review vocabulary",
            title: "Return to context, not just the definition.",
            body: "When reviewing, first recall which sentence the word came from and how it sounds, then listen to that line again. Review by ear rather than only reading the translation, so the word becomes listening vocabulary.",
            bullets: [
              "Recall the original sentence and sound first",
              "Listen to the original line again",
              "Review by ear, not only by definition",
            ],
          },
        ],
        faq: [
          {
            question: "How is a listening vocabulary different from ordinary word memorization?",
            answer: "A listening vocabulary comes from the real material you're practicing, so each word carries pronunciation and sentence context; ordinary lists are isolated words without context. The former is much easier to recognize in real listening.",
          },
          {
            question: "Should I save every new word?",
            answer: "Not necessarily. Prioritize words that truly block understanding and appear repeatedly; skip one-off proper nouns or rare words and spend the time on high-frequency, practical vocabulary.",
          },
          {
            question: "How often should I review vocabulary?",
            answer: "A quick pass before your next intensive session works well—plus listening to the original line again. Ongoing input from new material matters more than a strict spaced-repetition schedule.",
          },
        ],
      },
    },
  },
  {
    slug: "difficult-review",
    lastModified: "2026-09-01",
    ogImage: "/og-difficult-review.png",
    locales: {
      zh: {
        metaTitle: "难点复习：把时间花在真正听不懂的地方",
        metaDescription:
          "标记难点句子，集中复习真正听不懂的部分。DuolinTing 难点复习阶段帮你用最少的时间补上最大的听力短板，让每次练习都更接近听懂。",
        ogTitle: "难点复习｜把时间花在真正听不懂的地方",
        ogDescription: "标记难点句子，集中复习真正听不懂的部分，用最少的时间补上最大的短板。",
        ogAlt: "DuolinTing 多邻听——难点复习",
        hero: {
          eyebrow: "难点复习 · 第三阶段",
          title: "把时间，留给真正难的那几句。",
          lead: "难点复习是 DuolinTing 三阶段练习的收尾：把泛听和精听中标记出来的困难句子集中重练，让时间花在真正需要的地方。",
        },
        sections: [
          {
            eyebrow: "为什么需要复习",
            title: "听懂过一遍，不等于已经掌握。",
            body: "一次听懂很容易在第二天忘记。把难点句子集中起来复习，是对抗遗忘、把“听懂过”变成“一直听得懂”的关键一步。",
            bullets: [
              "把“听懂过”变成“一直听得懂”",
              "对抗遗忘曲线",
              "让练习闭环，而不是练完就丢",
            ],
          },
          {
            eyebrow: "怎么标记难点",
            title: "在精听中随手标记，复习时集中处理。",
            body: "在逐句精听时，把听不清、需要反复重听的句子标记为难点。它们会自动进入复习阶段，让你不必在整段材料里大海捞针。",
            bullets: [
              "精听时标记听不清的句子",
              "难点自动汇聚到复习阶段",
              "不必再翻整段材料找薄弱点",
            ],
          },
          {
            eyebrow: "怎么高效复习",
            title: "集中练难点，直到不用刻意也能听懂。",
            body: "复习阶段只做一件事：把标记出来的难点句子再听、再核对，直到在正常语速下也能自然听懂。集中、短时、高频，比漫无目的的重听更有效。",
            bullets: [
              "集中重听标记的难点句子",
              "再核对原文与译文",
              "直到原速也能自然听懂",
            ],
          },
        ],
        faq: [
          {
            question: "难点复习要练多久？",
            answer: "以把标记的难点句子在正常语速下听懂为目标，通常几分钟就能过一遍。关键是集中、短时、高频，而不是一次练到筋疲力尽。",
          },
          {
            question: "难点标记可以取消吗？",
            answer: "可以。当一句难点已经能稳定听懂，就可以解除标记；它不再占用复习时间，让你把注意力留给仍然不稳的句子。",
          },
          {
            question: "复习时还要再泛听吗？",
            answer: "如果标记的难点较多，可以先快速泛听一遍找回上下文，再集中精听难点；如果只有几句，直接进入复习即可。",
          },
        ],
      },
      en: {
        metaTitle: "Difficult-Line Review: Spend Time Where Listening Is Hardest",
        metaDescription:
          "Mark difficult lines and review only what you still can't catch. DuolinTing's review stage helps you close your biggest listening gaps in the least time, so every session moves you closer to understanding.",
        ogTitle: "Difficult-Line Review | Focus Where Listening Is Hardest",
        ogDescription: "Mark difficult lines and review them together, so your time goes where listening is actually hard.",
        ogAlt: "DuolinTing — difficult-line review",
        hero: {
          eyebrow: "Difficult review · Stage three",
          title: "Give your time to the lines that are still hard.",
          lead: "Difficult-line review is the final stage of DuolinTing's three-stage path: bring the hard lines you marked during warm-up and intensive practice back together, and spend your time where it matters.",
        },
        sections: [
          {
            eyebrow: "Why review",
            title: "Understanding once isn't the same as mastering.",
            body: "A line you understood once can fade by the next day. Gathering difficult lines for review is the step that turns “I understood it once” into “I still understand it.”",
            bullets: [
              "Turn “understood once” into “still understand”",
              "Work against forgetting",
              "Close the loop instead of dropping lines",
            ],
          },
          {
            eyebrow: "How to mark difficult lines",
            title: "Mark as you practice, handle together in review.",
            body: "During line-by-line practice, mark the lines you can't catch or need to replay. They automatically gather into the review stage, so you never have to hunt through a whole passage for weak spots.",
            bullets: [
              "Mark unclear lines during intensive practice",
              "Difficult lines gather automatically for review",
              "No need to re-scan the whole passage",
            ],
          },
          {
            eyebrow: "How to review efficiently",
            title: "Focus on difficult lines until they come naturally.",
            body: "The review stage does one thing: replay and re-check the marked lines until you understand them naturally at full speed. Focused, short, frequent sessions beat unfocused replay.",
            bullets: [
              "Replay only the marked difficult lines",
              "Re-check the source and translation",
              "Continue until full speed feels natural",
            ],
          },
        ],
        faq: [
          {
            question: "How long should difficult review take?",
            answer: "Aim to understand the marked lines at full speed—usually a few minutes is enough for a pass. The key is focused, short, frequent sessions rather than one exhausting marathon.",
          },
          {
            question: "Can I remove a difficult mark?",
            answer: "Yes. Once a line is reliably clear, remove its mark; it stops taking review time, leaving your attention for the lines that are still unstable.",
          },
          {
            question: "Should I warm up again before review?",
            answer: "If you marked many difficult lines, a quick extensive pass can restore context before you focus on the hard lines; with only a few, you can jump straight into review.",
          },
        ],
      },
    },
  },
];

/** Look up a single landing page by its URL slug. Returns undefined for unknown slugs. */
export function getLandingPage(slug: string): LandingPage | undefined {
  return landingPages.find((page) => page.slug === slug);
}

/**
 * Localized public path for a landing page: `/practice/<slug>` for Chinese,
 * `/en/practice/<slug>` for English. Used by generateMetadata (canonical /
 * hreflang) and internal links.
 */
export function landingPagePath(slug: string, locale: Locale): string {
  const base = `/practice/${slug}`;
  return locale === "en" ? `/en${base}` : base;
}
