import type { UiLocale } from '@duolinting/domain'

export const authSecurityMessages: Record<UiLocale, Record<string, string>> = {
  'zh-CN': { 'authSecurity.methods': '登录方式', 'authSecurity.enabled': '已绑定', 'authSecurity.disabled': '未绑定', 'authSecurity.setPassword': '设置密码', 'authSecurity.unlink': '解除关联', 'authSecurity.unlinkHint': '先重新验证身份，再解除 {{provider}}。不能解除最后一种登录方式。', 'authSecurity.delete': '删除账号', 'authSecurity.deleteHint': '此操作会永久删除账号和学习数据。请先重新验证身份。', 'authSecurity.deleteConfirm': '永久删除账号', 'authSecurity.actionFailed': '操作未完成，请重新验证后再试。', 'authSecurity.linkEmail': '设置邮箱登录', 'authSecurity.linkEmailHint': '验证邮箱后，也能用验证码登录此账号。', 'authSecurity.emailCollision': '这个邮箱已属于另一个账号。' },
  'en-US': { 'authSecurity.methods': 'Sign-in methods', 'authSecurity.enabled': 'Linked', 'authSecurity.disabled': 'Not linked', 'authSecurity.setPassword': 'Set password', 'authSecurity.unlink': 'Unlink', 'authSecurity.unlinkHint': 'Verify your identity before unlinking {{provider}}. Your final sign-in method cannot be removed.', 'authSecurity.delete': 'Delete account', 'authSecurity.deleteHint': 'This permanently removes your account and learning data. Verify your identity first.', 'authSecurity.deleteConfirm': 'Permanently delete account', 'authSecurity.actionFailed': 'This action did not finish. Verify again and retry.', 'authSecurity.linkEmail': 'Set up email sign-in', 'authSecurity.linkEmailHint': 'Verify your address to also access this account with an email code.', 'authSecurity.emailCollision': 'That email belongs to another account.' },
  'th-TH': { 'authSecurity.methods': 'วิธีเข้าสู่ระบบ', 'authSecurity.enabled': 'เชื่อมแล้ว', 'authSecurity.disabled': 'ยังไม่เชื่อม', 'authSecurity.setPassword': 'ตั้งรหัสผ่าน', 'authSecurity.unlink': 'ยกเลิกการเชื่อม', 'authSecurity.unlinkHint': 'ยืนยันตัวตนก่อนยกเลิก {{provider}} ไม่สามารถลบวิธีสุดท้ายได้', 'authSecurity.delete': 'ลบบัญชี', 'authSecurity.deleteHint': 'การดำเนินการนี้จะลบบัญชีและข้อมูลการเรียนถาวร โปรดยืนยันตัวตนก่อน', 'authSecurity.deleteConfirm': 'ลบบัญชีถาวร', 'authSecurity.actionFailed': 'ดำเนินการไม่สำเร็จ โปรดยืนยันตัวตนอีกครั้ง', 'authSecurity.linkEmail': 'ตั้งค่าอีเมล', 'authSecurity.linkEmailHint': 'ยืนยันอีเมลเพื่อใช้รหัสเข้าสู่บัญชีนี้', 'authSecurity.emailCollision': 'อีเมลนี้เป็นของอีกบัญชี' },
  'ja-JP': { 'authSecurity.methods': 'ログイン方法', 'authSecurity.enabled': '連携済み', 'authSecurity.disabled': '未連携', 'authSecurity.setPassword': 'パスワードを設定', 'authSecurity.unlink': '連携を解除', 'authSecurity.unlinkHint': '{{provider}} の解除前に本人確認をしてください。最後の方法は解除できません。', 'authSecurity.delete': 'アカウントを削除', 'authSecurity.deleteHint': 'アカウントと学習データが完全に削除されます。先に本人確認をしてください。', 'authSecurity.deleteConfirm': 'アカウントを完全に削除', 'authSecurity.actionFailed': '操作できませんでした。再確認してお試しください。', 'authSecurity.linkEmail': 'メールログインを設定', 'authSecurity.linkEmailHint': '確認後はメールコードでもログインできます。', 'authSecurity.emailCollision': 'このメールは別のアカウントで使用されています。' },
  'fr-FR': { 'authSecurity.methods': 'Méthodes de connexion', 'authSecurity.enabled': 'Lié', 'authSecurity.disabled': 'Non lié', 'authSecurity.setPassword': 'Définir un mot de passe', 'authSecurity.unlink': 'Dissocier', 'authSecurity.unlinkHint': 'Vérifiez votre identité avant de dissocier {{provider}}. La dernière méthode ne peut pas être retirée.', 'authSecurity.delete': 'Supprimer le compte', 'authSecurity.deleteHint': 'Votre compte et vos données d’apprentissage seront supprimés définitivement. Vérifiez votre identité.', 'authSecurity.deleteConfirm': 'Supprimer définitivement', 'authSecurity.actionFailed': 'L’opération n’a pas abouti. Vérifiez votre identité et réessayez.', 'authSecurity.linkEmail': 'Configurer la connexion par email', 'authSecurity.linkEmailHint': 'Après vérification, connectez-vous aussi avec un code envoyé par email.', 'authSecurity.emailCollision': 'Cette adresse appartient à un autre compte.' },
  'es-ES': { 'authSecurity.methods': 'Métodos de acceso', 'authSecurity.enabled': 'Vinculado', 'authSecurity.disabled': 'Sin vincular', 'authSecurity.setPassword': 'Crear contraseña', 'authSecurity.unlink': 'Desvincular', 'authSecurity.unlinkHint': 'Verifica tu identidad antes de desvincular {{provider}}. No puedes quitar el último método.', 'authSecurity.delete': 'Eliminar cuenta', 'authSecurity.deleteHint': 'Esto elimina permanentemente tu cuenta y datos de aprendizaje. Verifica tu identidad primero.', 'authSecurity.deleteConfirm': 'Eliminar permanentemente', 'authSecurity.actionFailed': 'No se completó la acción. Verifica tu identidad e inténtalo de nuevo.', 'authSecurity.linkEmail': 'Configurar acceso por correo', 'authSecurity.linkEmailHint': 'Tras verificar el correo, también podrás entrar con un código.', 'authSecurity.emailCollision': 'Este correo pertenece a otra cuenta.' },
}
