import type { UiLocale } from '@duolinting/domain'

export const sponsorMessages: Record<UiLocale, Record<string, string>> = {
  'zh-CN': { 'sponsors.nav': '赞助', 'sponsors.back': '返回学习', 'sponsors.title': '感谢赞助伙伴', 'sponsors.subtitle': '感谢这些伙伴支持多邻听，让更多人能持续练习听力。', 'sponsors.list': '赞助伙伴', 'sponsors.loading': '正在加载赞助伙伴…', 'sponsors.error': '赞助伙伴暂时无法加载，请稍后再试。', 'sponsors.empty': '目前还没有公开展示的赞助伙伴。', 'sponsors.visit': '访问官网' },
  'en-US': { 'sponsors.nav': 'Sponsors', 'sponsors.back': 'Back to learning', 'sponsors.title': 'Thanks to our sponsors', 'sponsors.subtitle': 'These partners help more people keep practicing their listening skills.', 'sponsors.list': 'Sponsors', 'sponsors.loading': 'Loading sponsors…', 'sponsors.error': 'Sponsors could not be loaded. Please try again later.', 'sponsors.empty': 'No sponsors are on display yet.', 'sponsors.visit': 'Visit website' },
  'th-TH': { 'sponsors.nav': 'ผู้สนับสนุน', 'sponsors.back': 'กลับไปเรียน', 'sponsors.title': 'ขอบคุณผู้สนับสนุน', 'sponsors.subtitle': 'พันธมิตรเหล่านี้ช่วยให้ผู้คนฝึกทักษะการฟังได้อย่างต่อเนื่อง', 'sponsors.list': 'ผู้สนับสนุน', 'sponsors.loading': 'กำลังโหลดผู้สนับสนุน…', 'sponsors.error': 'โหลดรายชื่อผู้สนับสนุนไม่ได้ โปรดลองอีกครั้งภายหลัง', 'sponsors.empty': 'ยังไม่มีผู้สนับสนุนที่แสดงต่อสาธารณะ', 'sponsors.visit': 'เยี่ยมชมเว็บไซต์' },
  'ja-JP': { 'sponsors.nav': 'スポンサー', 'sponsors.back': '学習に戻る', 'sponsors.title': 'スポンサーの皆さまに感謝', 'sponsors.subtitle': '皆さまの支援が、より多くの人のリスニング学習を支えています。', 'sponsors.list': 'スポンサー', 'sponsors.loading': 'スポンサーを読み込み中…', 'sponsors.error': 'スポンサーを読み込めませんでした。後でもう一度お試しください。', 'sponsors.empty': '現在、公開中のスポンサーはありません。', 'sponsors.visit': '公式サイトを見る' },
  'fr-FR': { 'sponsors.nav': 'Sponsors', 'sponsors.back': 'Retour aux cours', 'sponsors.title': 'Merci à nos sponsors', 'sponsors.subtitle': 'Ces partenaires aident davantage de personnes à pratiquer la compréhension orale.', 'sponsors.list': 'Sponsors', 'sponsors.loading': 'Chargement des sponsors…', 'sponsors.error': 'Impossible de charger les sponsors. Réessayez plus tard.', 'sponsors.empty': 'Aucun sponsor n’est affiché pour le moment.', 'sponsors.visit': 'Visiter le site' },
  'es-ES': { 'sponsors.nav': 'Patrocinadores', 'sponsors.back': 'Volver al aprendizaje', 'sponsors.title': 'Gracias a nuestros patrocinadores', 'sponsors.subtitle': 'Estos colaboradores ayudan a más personas a practicar la comprensión auditiva.', 'sponsors.list': 'Patrocinadores', 'sponsors.loading': 'Cargando patrocinadores…', 'sponsors.error': 'No se pudieron cargar los patrocinadores. Inténtalo más tarde.', 'sponsors.empty': 'Todavía no hay patrocinadores publicados.', 'sponsors.visit': 'Visitar sitio web' },
}
